# Generated by Django 4.2.23 on 2025-08-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_purchase_delete_boughtcars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=220),
        ),
    ]
